// <auto-generated />
namespace Code_frist_Demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class EmployeeEf_Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmployeeEf_Create));
        
        string IMigrationMetadata.Id
        {
            get { return "202512151114534_EmployeeEf_Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
